GET http://localhost:3000/characters

###

GET http://localhost:3000/characters/2

###

POST http://localhost:3000/characters
Content-Type: application/json

{ 
    "name": "Anna",
    "fairyTale": "Frost",
    "bestFriend": "Els"
}

###

PUT http://localhost:3000/characters/5
Content-Type: application/json

{  
    "name": "Anna",
    "fairyTale": "Frost",
    "bestFriend": "Elsa"
}

###

DELETE  http://localhost:3000/characters/5